name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  DOCKER_IMAGE_NAME_MP2: felixdumais1/ants_build_mp2
  DOCKER_IMAGE_NAME: felixdumais1/ants_build
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image MP2
      run: docker build . --file Dockerfile_mp2 --tag ${{ env.DOCKER_IMAGE_NAME_MP2 }}:latest 

    - name: Pushing Docker image MP2
      run: docker push ${{ env.DOCKER_IMAGE_NAME_MP2 }}:latest

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.DOCKER_IMAGE_NAME }}:latest 

    - name: Pushing Docker image
      run: docker push ${{ env.DOCKER_IMAGE_NAME }}:latest

